# Generated by Django 5.0 on 2024-06-18 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('department_name', models.CharField(error_messages={'unique': 'Given department already Existing'}, max_length=50, unique=True)),
                ('department_id', models.CharField(error_messages={'unique': 'Given id already Existing'}, max_length=10, unique=True)),
                ('phone', models.PositiveBigIntegerField(error_messages={'error': 'Given number is already used.'}, unique=True)),
                ('email', models.EmailField(blank=True, error_messages={'unique': 'Given Email Id is already used.'}, max_length=254, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['department_name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=15)),
                ('middle_name', models.CharField(blank=True, max_length=15, null=True)),
                ('last_name', models.CharField(max_length=15)),
                ('employee_id', models.CharField(error_messages={'unique': 'Given Employee Id is already exist.'}, max_length=10, null=True, unique=True)),
                ('date_of_birth', models.DateField()),
                ('phone', models.PositiveBigIntegerField(error_messages={'error': 'Given number is already used.'}, unique=True)),
                ('email', models.EmailField(error_messages={'unique': 'Given Email Id is already used.'}, max_length=254, unique=True)),
                ('designation', models.CharField(max_length=50)),
                ('date_of_join', models.DateField()),
                ('highest_degree', models.CharField(max_length=50)),
                ('total_experience', models.CharField(default='0', max_length=50)),
                ('is_working_here', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office_managementapp.department')),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('attendance_status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave')], max_length=25)),
                ('date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office_managementapp.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('bank_name', models.CharField(max_length=50)),
                ('account_number', models.PositiveBigIntegerField(error_messages={'unique': 'Given Account number is already Exist.'}, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='office_managementapp.employee')),
            ],
            options={
                'ordering': ['account_number'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.PositiveIntegerField()),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(default='India', max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office_managementapp.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('project_name', models.CharField(max_length=300)),
                ('project_id', models.CharField(error_messages={'unique': 'Given Project Id is existing'}, max_length=10, unique=True)),
                ('tech_used', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office_managementapp.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office_managementapp.employee')),
            ],
            options={
                'ordering': ['project_name'],
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('salary_id', models.IntegerField(error_messages={'unique': 'Generated random number has duplicate numberf'}, unique=True, verbose_name=5979)),
                ('remark', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office_managementapp.account')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office_managementapp.employee')),
            ],
            options={
                'ordering': ['amount'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('task_name', models.CharField(default='', max_length=300)),
                ('task_id', models.CharField(error_messages={'unique': 'Task Id is Existing'}, max_length=5, unique=True)),
                ('task_status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Complated')], max_length=25)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('task_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office_managementapp.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office_managementapp.project')),
            ],
            options={
                'ordering': ['task_name'],
            },
        ),
    ]
