# Generated by Django 5.0 on 2024-06-18 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office_managementapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='salary_id',
        ),
    ]
