# Generated by Django 5.0 on 2024-07-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0002_remove_salary_created_at_remove_salary_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('Current', 'Current'), ('Saving', 'Saving'), ('Salary', 'Salary'), ('Joint', 'Joint')], max_length=20),
        ),
    ]
