# Generated by Django 5.0 on 2024-07-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0004_alter_account_employee_alter_attendance_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_salary',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
