# Generated by Django 5.0 on 2024-06-09 17:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.PositiveBigIntegerField(unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('account_type', models.CharField(choices=[('Saving', 'Saving'), ('Current', 'Current'), ('Joint', 'Joint')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_id', models.CharField(error_messages={'unique': 'This bank_id is already used.'}, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_bank_id', message='Bank ID must contain both characters and numbers.', regex='^(?=.*[a-zA-Z])(?=.*\\d)[a-zA-Z\\d]*$')])),
                ('bank_type', models.CharField(choices=[('Goverment', 'Goverment'), ('Semi Goverment', 'Semi Goverment'), ('Private', 'Private'), ('Semi Private', 'Semi Private')], error_messages={'choices': 'Select correct given choice'}, max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.IntegerField(error_messages={'message': 'pincode must be integer'})),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(default='India', max_length=50)),
                ('phone', models.PositiveBigIntegerField(error_messages={'unique': 'Given phone number is already used'}, unique=True)),
                ('email', models.EmailField(error_messages={'unique': 'This email is already used.'}, max_length=40, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('father_name', models.CharField(max_length=30)),
                ('mother_name', models.CharField(max_length=30)),
                ('qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(default='India', max_length=50)),
                ('phone', models.PositiveBigIntegerField()),
                ('email', models.EmailField(blank=True, max_length=40, null=True, unique=True)),
                ('is_alive', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bankapp.account')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100)),
                ('branch_id', models.CharField(max_length=10, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('pincode', models.IntegerField()),
                ('country', models.CharField(default='India', max_length=50)),
                ('phone', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankapp.bank')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankapp.branch'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Deposit', 'Deposit'), ('Credit', 'Credit')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=3, default=0, max_digits=30)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankapp.account')),
            ],
        ),
    ]
