# Generated by Django 5.0 on 2024-06-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='pincode',
            field=models.IntegerField(error_messages={'invalid': 'Pincode must be an integer.'}),
        ),
    ]
