# Generated by Django 5.0 on 2024-06-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_account_deleted_at_accountholder_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountholder',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'Given Email id is already used.'}, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
