# Generated by Django 5.0 on 2024-06-11 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0004_alter_accountholder_email_alter_bank_pincode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['account_number']},
        ),
        migrations.AlterModelOptions(
            name='accountholder',
            options={'ordering': ['holder_name']},
        ),
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['bank_name']},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['branch_name']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['transaction_date']},
        ),
    ]
