# Generated by Django 5.0 on 2024-06-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0005_alter_account_options_alter_accountholder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email id is already used.'}, max_length=40, unique=True),
        ),
    ]
