# Generated by Django 5.0 on 2024-06-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0006_alter_bank_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank_name',
            field=models.CharField(error_messages={'errors': 'Bank Name should not be blank'}, max_length=100),
        ),
    ]
