# Generated by Django 5.0 on 2024-06-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0009_alter_bank_bank_id_alter_bank_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank_name',
            field=models.CharField(max_length=100),
        ),
    ]
