# Generated by Django 5.0 on 2024-06-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0010_alter_bank_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank_id',
            field=models.CharField(error_messages={'unique': 'Given bank_id is already used.'}, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_id',
            field=models.CharField(error_messages={'unique': 'Given Branch Id is already used.'}, max_length=10, unique=True),
        ),
    ]
