# Generated by Django 5.0 on 2024-06-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0016_alter_bank_bank_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('Saving', 'Saving'), ('Current', 'Current'), ('Joint', 'Joint')], max_length=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrow', 'Withdrow')], max_length=20),
        ),
    ]
