# Generated by Django 5.0 on 2024-06-16 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0017_alter_account_account_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={},
        ),
        migrations.AlterModelOptions(
            name='accountholder',
            options={},
        ),
        migrations.AlterModelOptions(
            name='bank',
            options={},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={},
        ),
    ]
