# Generated by Django 5.0 on 2024-07-20 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0024_alter_account_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='bankapp.account'),
        ),
    ]
